version: '3.1'

services:
  mysql:
    container_name: todolist-mysql-db
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      MYSQL_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
  web:
    build: .
    container_name: todolist-web-app
    ports:
      - '8080:8080'
    depends_on:
      - mysql