version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todolist-web-app
    ports:
      - '8080:8080'
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      PORT: 8080
      GIN_MODE: release
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: todolist
      DB_DRIVER: mysql
      APP_LOG_LEVEL: info
    restart: on-failure
  mysql:
    container_name: todolist-mysql-db
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: todolist
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD-SHELL", "echo 'select 1' | mysql -u root -p'root' --silent"]
      timeout: 10s
      retries: 5